version: '3.8'

services:
  backend:
    build: .
    ports:
      - 3000:3000
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
  redis:
    image: redis
    command: ["redis-server", "--bind", "redis", "--port", "6379"]
    ports:
      - 6379:6379

